const produtos = [
    {
        id:1,
        img:"./src/img-produtos/O Mandaloriano.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"O Mandaloriano",
        tipo:"Star Wars: Mandalorian",
        cor:"Multicor",
        peso:"20 gramas",
        dimencoes:"15.2 x 15.2 x 25.4 centímetros",
        quantidade:20,
        valor:484,
        desconto:450,
        descontoAtivo:true,
    },
    {
        id:2,
        img:"./src/img-produtos/Darth Vaider.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Darth Vaider",
        tipo:"Star Wars",
        cor:"Multicor",
        peso:"100 gramas",
        dimencoes:"6.4 x 6.4 x 9.5 centímetros",
        quantidade:5,
        valor:338,
        desconto:320,
        descontoAtivo:true,
    },
    {
        id:3,
        img:"./src/img-produtos/Obi Wan Kenobi.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Obi Wan Kenobi",
        tipo:"Star Wars",
        cor:"Multicor",
        peso:"90 gramas",
        dimencoes:"7.6 x 7.6 x 9.5 centímetros",
        quantidade:2,
        valor:455,
        desconto:400,
        descontoAtivo:true,
    },
    {
        id:4,
        img:"./src/img-produtos/Ahsoka.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Ahsoka",
        tipo:"Star Wars:The Mandalorian",
        cor:"Multicor",
        peso:"70 gramas",
        dimencoes:"6.4 x 6.4 x 9.5 centímetros",
        quantidade:10,
        valor:119,
        desconto:100,
        descontoAtivo:true,
    },
    {
        id:5,
        img:"./src/img-produtos/Boba Fett.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Boba Fett",
        tipo:"Star Wars:The Mandalorian",
        cor:"Multicor",
        peso:"100 gramas",
        dimencoes:"6.4 x 6.4 x 9.5 centímetros",
        quantidade:20,
        valor:119,
        desconto:98,
        descontoAtivo:true,
    },
    {
        id:6,
        img:"./src/img-produtos/Qui-Gon Jinn.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Qui-Gon Jinn",
        tipo:"Star Wars",
        cor:"Multicor",
        peso:"90 gramas",
        dimencoes:"6.4 x 6.4 x 9.5 centímetros",
        quantidade:30,
        valor:159,
        desconto:150,
        descontoAtivo:true,
    },
    {
        id:7,
        img:"./src/img-produtos/Palpatine.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Palpatine",
        tipo:"Star Wars",
        cor:"Multicor",
        peso:"70 gramas",
        dimencoes:"6.4 x 6.4 x 9.5 centímetros",
        quantidade:15,
        valor:139,
        desconto:130,
        descontoAtivo:true,
    },
    {
        id:8,
        img:"./src/img-produtos/Luke Skywalker.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Luke Skywalker",
        tipo:"Star Wars",
        cor:"Multicor",
        peso:"90 gramas",
        dimencoes:"6.4 x 6.4 x 9.5 centímetros",
        quantidade:12,
        valor:149,
        desconto:145,
        descontoAtivo:true,
    },
    {
        id:9,
        img:"./src/img-produtos/Darth Maul.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Darth Maul",
        tipo:"Star Wars",
        cor:"Multicor",
        peso:"100 gramas",
        dimencoes:"7.6 x 7.6 x 9.5 centímetros",
        quantidade:12,
        valor:174,
        desconto:170,
        descontoAtivo:true,
    },
    {
        id:10,
        img:"./src/img-produtos/Bo-Katan.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Bo-Katan",
        tipo:"Star Wars:The Mandalorian",
        cor:"Multicor",
        peso:"90 gramas",
        dimencoes:"7.6 x 7.6 x 9.5 centímetros",
        quantidade:12,
        valor:99,
        desconto:90,
        descontoAtivo:true,
    },
    {
        id:11,
        img:"./src/img-produtos/Dark Trooper.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Dark Trooper",
        tipo:"Star Wars:The Mandalorian",
        cor:"Multicor",
        peso:"110 gramas",
        dimencoes:"6.4 x 6.4 x 9.5 centímetros",
        quantidade:20,
        valor:98,
        desconto:90,
        descontoAtivo:true,
    },
    {
        id:12,
        img:"./src/img-produtos/Cara Dune.jpg",
        imgBotao:"./src/img/Carrinho_cheio.svg",
        nome:"Cara Dune",
        tipo:"Star Wars:The Mandalorian",
        cor:"Multicor",
        peso:"95 gramas",
        dimencoes:"7.6 x 7.6 x 9.5 centímetros",
        quantidade:15,
        valor:119,
        desconto:95,
        descontoAtivo:true,
    },
    
]